#! /bin/python3

import argparse
import os
import requests

url = ""
with open(os.path.expanduser("~/.config/microbin-clients/server")) as f:
    url = f.readline().strip()

argparser = argparse.ArgumentParser(
    prog="Microbin Client CLI",
    description="A command line client to upload files or text to your microbin instance",
)
argparser.add_argument(
    '-f',
    dest="file",
    type=argparse.FileType('rb'),
    default=None
)
argparser.add_argument(
    '-t',
    dest="content",
    default=None
)
argparser.add_argument(
    '-n',
    dest="editable",
    action='store_false'
)
argparser.add_argument(
    '-e',
    dest="expiration",
    default='never',
    choices=[
            'never',
            '1min',
            '10min',
            '1hour',
            '24hour',
            '1week'
    ]
)
parsed_args = argparser.parse_args()

if parsed_args.content == None and parsed_args.file == None:
    print("Nothing to upload")
    exit(1)

data = {
    "expiration": parsed_args.expiration,
    "content": parsed_args.content,
    "editable": parsed_args.editable,
    "syntax-highlight": "none"
}
response = requests.post(url+"/upload", files={"file": parsed_args.file}, data=data)
response.raise_for_status()
print(response.url)
